#!/bin/bash

gs -q -dNOPAUSE -dBATCH \
    -dSAFER \
    -sDEVICE=pdfwrite \
    -sProcessColorModel=DeviceGray \
    -sColorConversionStrategy=Gray \
    -dOverrideICC \
    -dCompatibilityLevel=1.3 \
    -dPDFSETTINGS=/screen \
    -dEmbedAllFonts=true \
    -dSubsetFonts=true \
    -dColorImageDownsampleType=/Bicubic \
    -dColorImageResolution=144 \
    -dGrayImageDownsampleType=/Bicubic \
    -dGrayImageResolution=144 \
    -dMonoImageDownsampleType=/Bicubic \
    -dMonoImageResolution=144 \
    -sOutputFile=${1%.*}.compressed.pdf $1; 

exit 0
