* Personal Information
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Julian Thome"
      user-mail-address "julian.thome.de@gmail.com"
      calendar-latitude 49.815273
      calendar-longitude 6.129583
      calendar-location-name "Luxembourg")
#+END_SRC

* Useful functions

Read lines from file into list if file exists. It does not report and error
message for non-existing files.

#+BEGIN_SRC emacs-lisp
(defun read-lines (filePath)
  "Return a list of lines of a file at filePath."
  (if (file-exists-p filePath)
      (with-temp-buffer
            (insert-file-contents filePath)
                  (split-string (buffer-string) "\n" t))
    ""
    )
)
#+END_SRC

List files under directory dir.

#+BEGIN_SRC emacs-lisp
(defun find-file-by-ext (dir ext) 
  (directory-files dir nil (concat "\\." ext "$")))
#+END_SRC

* Sensible default settings

Some sensible default settings some of which were taken from Harry
Schwartz' sensible default package https://github.com/hrs.

Disable backup.

#+BEGIN_SRC emacs-lisp
(setq make-backup-files nil)
#+END_SRC

Highlight current line.

#+BEGIN_SRC emacs-lisp
(global-hl-line-mode 1)
#+END_SRC

Local variables.

Always set safe variables and ignore the others.

#+BEGIN_SRC emacs-lisp
(setq enable-local-variables :safe)
#+END_SRC

Increase the limit before calling garbage collection.

#+BEGIN_SRC emacs-lisp
(setq gc-cons-threshold 20000000)
#+END_SRC

Always follow symlinks.

#+BEGIN_SRC emacs-lisp
(setq vc-follow-symlinks t)
#+END_SRC

Don't assume that sentences should have two spaces after
period.

#+BEGIN_SRC emacs-lisp
(setq sentence-end-double-space nil)
#+END_SRC

Enable transient mark mode.

#+BEGIN_SRC emacs-lisp
(transient-mark-mode t)
#+END_SRC

Delete selected text when providing input.
#+BEGIN_SRC emacs-lisp
(delete-selection-mode 1) 
#+END_SRC

Do not present the startup messge; clear scratch buffer.

#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)
(setq initial-scratch-message nil)
#+END_SRC

Human readable units.

#+BEGIN_SRC emacs-lisp
(setq-default dired-listing-switches "-alh")
#+END_SRC

Don't ask `yes/no?', ask `y/n?'.

#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

Enable syntax highlighting. 

#+BEGIN_SRC emacs-lisp
(global-font-lock-mode t)
#+END_SRC

Automatically sync buffer after file change.

#+BEGIN_SRC emacs-lisp
(global-auto-revert-mode t)
#+END_SRC

Highlight matching parens.
#+BEGIN_SRC emacs-lisp
(show-paren-mode 1)
(setq show-paren-delay 0.0)
#+END_SRC

Do not hightlight text inside parens

#+BEGIN_SRC emacs-lisp
(setq show-paren-style 'parenthesis)
#+END_SRC

When you perform a problematic operation, flash the screen
instead of ringing the terminal bell.

#+BEGIN_SRC emacs-lisp
(setq visible-bell t)
#+END_SRC

Turn off alarms completely.

#+BEGIN_SRC emacs-lisp
(setq ring-bell-function 'ignore)
#+END_SRC


Set the default line length to 80.

#+BEGIN_SRC emacs-lisp
(setq-default fill-column 80)
#+END_SRC

When you double-click on a file in the Mac Finder open it as a
buffer in the existing Emacs frame, rather than creating a new
frame just for that file.

#+BEGIN_SRC emacs-lisp
(setq ns-pop-up-frames nil)
#+END_SRC

Store backups and auto-saved files in /tmp.

#+BEGIN_SRC emacs-lisp
(defun backup-to-temp-directory ()
  (setq backup-directory-alist
        `((".*" . ,temporary-file-directory)))
  (setq auto-save-file-name-transforms
        `((".*" ,temporary-file-directory t))))

#+END_SRC

Keybindings.

#+BEGIN_SRC emacs-lisp
(setq default-font "Source Code Pro")
(setq default-font-size 16)
(setq current-font-size default-font-size)

(setq font-change-increment 1.1)

(defun font-code ()
  "Return a string representing the current font"
  (concat default-font "-" (number-to-string current-font-size)))

(defun set-font-size ()
  "Set the font to `default-font' at `current-font-size'.
Set that for the current frame, and also make it the default for
other, future frames."
  (let ((font-code (font-code)))
    (add-to-list 'default-frame-alist (cons 'font font-code))
    (set-frame-font font-code)))

(defun reset-font-size ()
  "Change font size back to `default-font-size'."
  (interactive)
  (setq current-font-size default-font-size)
  (set-font-size))

(defun increase-font-size ()
  "Increase current font size by a factor of `font-change-increment'."
  (interactive)
  (setq current-font-size
        (ceiling (* current-font-size font-change-increment)))
  (set-font-size))

(defun decrease-font-size ()
  "Decrease current font size by a factor of `font-change-increment', down to a minimum size of 1."
  (interactive)
  (setq current-font-size
        (max 1
             (floor (/ current-font-size font-change-increment))))
  (set-font-size))

(define-key global-map (kbd "C-)") 'reset-font-size)
(define-key global-map (kbd "C-+") 'increase-font-size)
(define-key global-map (kbd "C-=") 'increase-font-size)
(define-key global-map (kbd "C-_") 'decrease-font-size)
(define-key global-map (kbd "C--") 'decrease-font-size)

(reset-font-size)
#+END_SRC

Save place.

#+BEGIN_SRC emacs-lisp
(require 'saveplace)
(setq auto-save-default nil)
(setq save-place-file "~/.emacs.d/saveplace")
(setq-default save-place t)
#+END_SRC

Iterm Mouse settings.

#+BEGIN_SRC emacs-lisp
(unless window-system
  (require 'mouse)
  (xterm-mouse-mode t)
  (defun track-mouse (e)) 
  (setq mouse-sel-mode t)
)
#+END_SRC

Show column no in mode line.

#+BEGIN_SRC emacs-lisp
(column-number-mode nil)
#+END_SRC

Backwards compatibility as default-buffer-file-coding-system
is deprecated in 23.2.

#+BEGIN_SRC emacs-lisp 
(if (boundp 'buffer-file-coding-system)
    (setq-default buffer-file-coding-system 'utf-8)
  (setq default-buffer-file-coding-system 'utf-8))
#+END_SRC


Define the global encoding as utf-8 english US related.

#+BEGIN_SRC emacs-lisp
(setq system-time-locale "en_US.utf8")
(prefer-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
#+END_SRC

* Melpa
** General config
Setup emacs package manager.

#+BEGIN_SRC emacs-lisp

(require 'package)
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))

(setq package-enable-at-startup nil)
(package-initialize)

(defun ensure-package-installed (&rest packages)
  "Assure every package is installed, ask for installation if it's not.
Return a list of installed packages or nil for every skipped package."
  (mapcar
   (lambda (package)
     (if (package-installed-p package)
	 nil
       (if (y-or-n-p (format  "Package %s is missing. Install it? " package))
	   (package-install package)
	 package)))
   packages))

;; Make sure to have downloaded archive description.
(or (file-exists-p package-user-dir)
    (package-refresh-content))

;; Activate installed packages.
(package-initialize)
#+END_SRC

** Packages

#+BEGIN_SRC emacs-lisp
(ensure-package-installed
      'helm 
      'evil 
      'evil-org
      'evil-surround
      'key-chord 
      'doom-themes 
      'fill-column-indicator
      'general 
      'hydra 
      'auctex 
      'flycheck 
      'exec-path-from-shell 
      'neotree 
      'auctex-latexmk 
      'org-bullets 
      'org-journal
      'powerline 
      'airline-themes 
      'solarized-theme 
      'helm-bibtex 
      'evil-magit 
      'flyspell
      'projectile
      'helm-projectile
)
#+END_SRC

* UI configuration

** General
Use nice lambdas.

#+BEGIN_SRC emacs-lisp
(global-prettify-symbols-mode t)
#+END_SRC

#+BEGIN_SRC emacs-lisp
;; no menu and scroll bars
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
#+END_SRC

Column indicator.

#+BEGIN_SRC emacs-lisp
(require 'fill-column-indicator)
(setq fci-rule-width 1)
(setq fci-rule-column 80)
(add-hook 'after-change-major-mode-hook 'fci-mode)
(setq fci-rule-color "#a4adbc")
(setq fci-rule-character ?\u2502)
#+END_SRC


** Linum

#+BEGIN_SRC emacs-lisp
;; relative numbering
(linum-mode)
(linum-relative-global-mode)
#+END_SRC

** Airline

#+BEGIN_SRC emacs-lisp
(setq evil-emacs-state-cursor '("chartreuse3" (bar . 2)))
(require 'powerline)
(require 'airline-themes)
#+END_SRC

** Doom Theme

#+BEGIN_SRC emacs-lisp
(require 'doom-themes)

;; Global settings (defaults)
(setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
      doom-themes-enable-italic t
      nlinum-highlight-current-line t) ; if nil, italics is universally disabled

;; Load the theme (doom-one, doom-molokai, etc); keep in mind that each theme
;; may have their own settings.
(load-theme 'doom-one t)

(setq doom-line-numbers-style 'relative)

;; Enable flashing mode-line on errors
(doom-themes-visual-bell-config)

;; Corrects (and improves) org-mode's native fontification.
(doom-themes-org-config)
(set-face-attribute 'org-level-1 nil :height 1.0)
(load-theme 'airline-doom-one t)
#+END_SRC

* Latex Packages

** AucTex

#+BEGIN_SRC emacs-lisp
;; AucTeX
(setq-default TeX-master nil)
(setq TeX-parse-self t) ; Enable parse on load.
(setq TeX-auto-save t) ; Enable parse on save.

(add-hook 'LaTeX-mode-hook 'visual-line-mode)
(add-hook 'LaTeX-mode-hook 'flyspell-mode)
(add-hook 'LaTeX-mode-hook 'LaTeX-math-mode)
(add-hook 'LaTeX-mode-hook 'turn-on-reftex)

(setq reftex-plug-into-AUCTeX t)
(setq TeX-PDF-mode t)
 
;; make latexmk available via C-c C-c
;; Note: SyncTeX is setup via ~/.latexmkrc (see below)
(add-hook 'LaTeX-mode-hook (lambda ()
  (push
    '("latexmk" "latexmk %s" TeX-run-TeX nil t
      :help "Run latexmk on file")
    TeX-command-list)))
(add-hook 'TeX-mode-hook '(lambda () (setq TeX-command-default "latexmk")))

;; use Skim as default pdf viewer
;; Skim's displayline is used for forward search (from .tex to .pdf)
;; option -b highlights the current line; option -g opens Skim in the background  
(setq TeX-view-program-selection '((output-pdf "PDF Viewer")))
(setq TeX-view-program-list
     '(("PDF Viewer" "/Applications/Skim.app/Contents/SharedSupport/displayline -b -g %n %o %b")))

(add-hook 'TeX-mode-hook 'reftex-mode)
(add-hook 'LaTeX-mode-hook 'TeX-source-correlate-mode)
(setq TeX-source-correlate-method 'synctex)
(server-start) 
#+END_SRC

*** LatexMk

#+BEGIN_SRC
(auctex-latexmk-setup)
#+END_SRC

** NeoTree

#+BEGIN_SRC emacs-lisp
(require 'neotree)
(custom-set-faces
(set-face-attribute 'neo-button-face      nil :height 140)
(set-face-attribute 'neo-file-link-face   nil :height 140)
(set-face-attribute 'neo-dir-link-face    nil :height 140)
(set-face-attribute 'neo-header-face      nil :height 140)
(set-face-attribute 'neo-expand-btn-face  nil :height 140)
)
(setq neo-theme 'arrow)

(add-hook 'neotree-mode-hook
  (lambda ()
    (define-key evil-normal-state-local-map (kbd "TAB") 'neotree-enter)
    (define-key evil-normal-state-local-map (kbd "SPC") 'neotree-quick-look)
    (define-key evil-normal-state-local-map (kbd "q") 'neotree-hide)
    (define-key evil-normal-state-local-map (kbd "RET") 'neotree-enter)))
#+END_SRC

** Evil Mode

#+BEGIN_SRC emacs-lisp
(require 'key-chord)
(require 'evil)
(require 'hydra)
(require 'evil-surround)
(evil-mode 1)
(require 'general)
(general-evil-setup)
(key-chord-mode 1)

;; enable replacement in visual selection per default
(setq evil-ex-visual-char-range t)
;;(define-key evil-normal-state-map (kbd "]b") 'next-buffer)
;;(define-key evil-normal-state-map (kbd "[b") 'previous-buffer)
;;(define-key evil-normal-state-map (kbd "C-S-h") 'evil-window-left)
;;(define-key evil-normal-state-map (kbd "C-S-j") 'evil-window-down)
;;(define-key evil-normal-state-map (kbd "C-S-k") 'evil-window-up)
;;(define-key evil-normal-state-map (kbd "C-S-l") 'evil-window-right):w

(define-key evil-normal-state-map (kbd "C-u") 'evil-scroll-up)
(define-key evil-normal-state-map (kbd "C-d") 'evil-scroll-down)
(define-key evil-insert-state-map (kbd "ESC") 'evil-normal-state)
(general-nmap "Q" (general-simulate-key "gqap"))
(general-vmap "Q" (general-simulate-key "gq"))

(key-chord-define evil-normal-state-map "jk" 'evil-force-normal-state)
(key-chord-define evil-visual-state-map "jk" 'evil-change-to-previous-state)
(key-chord-define evil-insert-state-map "jk" 'evil-normal-state)
(key-chord-define evil-replace-state-map "jk" 'evil-normal-state)

(key-chord-define evil-normal-state-map "ee" 'evil-emacs-state)
;; having words with 'ee' is quite common - so do not use this in insert mode
;;(key-chord-define evil-insert-state-map "ee" 'evil-emacs-state)
(key-chord-define evil-emacs-state-map "ee" 'evil-normal-state)

(defvar comma-leader-map (make-sparse-keymap)
  "Keymap for \"leader key\" shortcuts.")
(define-key evil-normal-state-map "," comma-leader-map)


(defvar bracket-leader-map (make-sparse-keymap)
  "Keymap for \"leader key\" shortcuts.")
(define-key evil-normal-state-map "[" bracket-leader-map)

(defun my-run-latex ()
  (interactive)
  (TeX-save-document (TeX-master-file))
  (TeX-command "latexmk" 'TeX-master-file -1))


(define-key comma-leader-map "lr" 'my-run-latex)
(define-key comma-leader-map "ls" 'TeX-view)

(define-key comma-leader-map "bn" 'next-buffer)
(define-key comma-leader-map "bp" 'previous-buffer)


;; change the "leader" key to space
;; (define-key evil-normal-state-map "," 'evil-repeat-find-char-reverse)
;; (define-key evil-normal-state-map (kbd "SPC") comma-leader-map)

(defun close-and-kill-this-pane ()
      "If there are multiple windows, then close this pane and kill the buffer in it also."
      (interactive)
      (kill-this-buffer)
      (if (not (one-window-p))
          (delete-window)))

(define-key comma-leader-map "bd" 'close-and-kill-this-pane)
(define-key comma-leader-map "x" 'save-buffers-kill-emacs)
(define-key comma-leader-map "f" 'neotree-toggle)

#+END_SRC


Enable surround everywhere.

#+BEGIN_SRC emacs-lisp
(global-evil-surround-mode 1)
#+END_SRC

** Projectile

Enable projectile with helm support.

#+BEGIN_SRC emacs-lisp
(projectile-global-mode)
(setq projectile-completion-system 'helm)
(helm-projectile-on)
#+END_SRC

Enable caching.

#+BEGIN_SRC emacs-lisp
(setq projectile-enable-caching t)
#+END_SRC

** Helm

#+BEGIN_SRC emacs-lisp
(require 'helm)
(require 'helm-bibtex)
(setq helm-for-files-preferred-list '(helm-source-buffers-list
                                      helm-source-buffer-not-found
                                      helm-source-recentf
                                      helm-source-bookmarks
                                      helm-source-file-cache
                                      helm-source-files-in-current-dir
                                      ))

;;(define-key evil-normal-state-map (kbd "C-p") 'helm-multi-files)
(define-key evil-normal-state-map (kbd "C-p") 'projectile-find-file)
(define-key helm-map (kbd "C-j") 'helm-next-line)
(define-key helm-map (kbd "C-k") 'helm-previous-line)
(autoload 'helm-bibtex "helm-bibtex" "" t)
(setq bibtex-completion-bibliography (find-file-by-ext (projectile-project-root) "bib"))
(setq helm-bibtex-bibliography (find-file-by-ext (projectile-project-root) "bib"))
#+END_SRC

** Linting
*** Flycheck

#+BEGIN_SRC emacs-lisp
(package-install 'flycheck)
(global-flycheck-mode)
(exec-path-from-shell-initialize)
#+END_SRC

*** Flyspell

#+BEGIN_SRC emacs-lisp
(require 'flyspell)
(dolist (hook '(text-mode-hook))
  (add-hook hook (lambda () (flyspell-mode 1))))
#+END_SRC

** Git

Git support for Emacs

#+BEGIN_SRC emacs-lisp
(require 'evil-magit)
#+END_SRC

** Org

Org states.

#+BEGIN_SRC emacs-lisp 
(setq org-todo-keywords
  '((sequence "TODO" "WAIT" "|" "DONE" "CANCELED")))
#+END_SRC

Archiving.

#+BEGIN_SRC emacs-lisp
(setq org-archive-mark-done nil)
(setq org-archive-location "%s_archive::* Archived Tasks")
(require 'org-journal)
#+END_SRC

Org Journal.

#+BEGIN_SRC emacs-lisp
(require 'org-journal)
#+END_SRC

Pretty org bullets.

#+BEGIN_SRC emacs-lisp
(require 'org)
(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+END_SRC

Evil keybindings.

#+BEGIN_SRC emacs-lisp
(require 'evil-org)
(add-hook 'org-mode-hook 'evil-org-mode)
(evil-org-set-key-theme '(navigation insert textobjects additional calendar))
(require 'evil-org-agenda)
(evil-org-agenda-set-keys)
#+END_SRC

Arrow that point downwards instead of ellipsis in org mode.

#+BEGIN_SRC emacs-lisp
(setq org-ellipsis "⤵")
#+END_SRC

Global todo list.

#+BEGIN_SRC emacs-lisp
(setq org-agenda-files (read-lines "~/org/todo.txt"))
#+END_SRC
